# Generated by Django 5.0.14 on 2025-11-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum_post",
            name="post_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forums",
            name="meeting_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mon", "Monday"),
                    ("Tue", "Tuesday"),
                    ("Wed", "Wednesday"),
                    ("Thu", "Thursday"),
                    ("Fri", "Friday"),
                    ("Sat", "Saturday"),
                    ("Sun", "Sunday"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="forums",
            name="meeting_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forums",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
