# Generated by Django 5.2.8 on 2025-11-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_products_prodcut_stripe_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="prodcut_link",
            new_name="product_description",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="prodcut_name",
            new_name="product_link",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="product_discription",
            new_name="product_name",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="prodcut_stripe_id",
            new_name="product_stripe_id",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="prodcut_tags",
            new_name="product_tags",
        ),
    ]
